language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
after_script:
  - npm run report-coverage
branches:
  only:
    - master
    - /^greenkeeper/.*$/
